# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '20241025-火灾检测预备材料/QTtest3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 191, 91))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(183, 243, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_open_close_camera = QtWidgets.QPushButton(self.frame)
        self.pushButton_open_close_camera.setGeometry(QtCore.QRect(90, 10, 93, 28))
        self.pushButton_open_close_camera.setObjectName("pushButton_open_close_camera")
        self.pushButton_open_close_distinguish = QtWidgets.QPushButton(self.frame)
        self.pushButton_open_close_distinguish.setGeometry(QtCore.QRect(90, 50, 93, 28))
        self.pushButton_open_close_distinguish.setObjectName("pushButton_open_close_distinguish")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 100, 191, 91))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(183, 243, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_select_photo = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_select_photo.setGeometry(QtCore.QRect(90, 10, 93, 28))
        self.pushButton_select_photo.setObjectName("pushButton_select_photo")
        self.pushButton_img_distinguish = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_img_distinguish.setGeometry(QtCore.QRect(90, 50, 93, 28))
        self.pushButton_img_distinguish.setObjectName("pushButton_img_distinguish")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 200, 191, 91))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(183, 243, 255);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_select_video = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_select_video.setGeometry(QtCore.QRect(90, 10, 93, 28))
        self.pushButton_select_video.setObjectName("pushButton_select_video")
        self.pushButton_video_distinguish = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_video_distinguish.setGeometry(QtCore.QRect(90, 50, 93, 28))
        self.pushButton_video_distinguish.setObjectName("pushButton_video_distinguish")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(210, 10, 341, 271))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(40, 50, 72, 20))
        self.label.setObjectName("label")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(570, 10, 431, 261))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(710, 310, 291, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.widget_conf = QtWidgets.QWidget(self.centralwidget)
        self.widget_conf.setGeometry(QtCore.QRect(20, 300, 661, 61))
        self.widget_conf.setProperty("oarent", "")
        self.widget_conf.setObjectName("widget_conf")

        self.widget_conf.sl = QtWidgets.QSlider(self.widget_conf)
        self.widget_conf.sl.setGeometry(QtCore.QRect(150, 40, 160, 22))
        self.widget_conf.sl.setOrientation(QtCore.Qt.Horizontal)
        self.widget_conf.sl.setObjectName("sl")

        self.radioButton_yolo_half_false = QtWidgets.QRadioButton(self.widget_conf)
        self.radioButton_yolo_half_false.setGeometry(QtCore.QRect(480, 20, 115, 19))
        self.radioButton_yolo_half_false.setObjectName("radioButton_yolo_half_false")

        self.widget_iou = QtWidgets.QWidget(self.centralwidget)
        self.widget_iou.setGeometry(QtCore.QRect(20, 380, 661, 51))
        self.widget_iou.setObjectName("widget_iou")

        self.widget_iou.sl_2 = QtWidgets.QSlider(self.widget_iou)
        self.widget_iou.sl_2.setGeometry(QtCore.QRect(170, 10, 160, 22))
        self.widget_iou.sl_2.setOrientation(QtCore.Qt.Horizontal)
        self.widget_iou.sl_2.setObjectName("sl_2")

        self.radioButton_yolo_nms_false = QtWidgets.QRadioButton(self.widget_iou)
        self.radioButton_yolo_nms_false.setGeometry(QtCore.QRect(500, 10, 115, 19))
        self.radioButton_yolo_nms_false.setObjectName("radioButton_yolo_nms_false")

        self.widget_max_det = QtWidgets.QWidget(self.centralwidget)
        self.widget_max_det.setGeometry(QtCore.QRect(20, 440, 661, 80))
        self.widget_max_det.setObjectName("widget_max_det")

        self.widget_max_det.sl_3 = QtWidgets.QSlider(self.widget_max_det)
        self.widget_max_det.sl_3.setGeometry(QtCore.QRect(170, 30, 160, 22))
        self.widget_max_det.sl_3.setOrientation(QtCore.Qt.Horizontal)
        self.widget_max_det.sl_3.setObjectName("sl_3")

        self.radioButton_yolo_line_2 = QtWidgets.QRadioButton(self.widget_max_det)
        self.radioButton_yolo_line_2.setGeometry(QtCore.QRect(480, 30, 115, 19))
        self.radioButton_yolo_line_2.setObjectName("radioButton_yolo_line_2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_open_close_camera.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_open_close_distinguish.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_select_photo.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_img_distinguish.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_select_video.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_video_distinguish.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "label"))
        self.label_2.setText(_translate("MainWindow", "label_2"))
        self.radioButton_yolo_half_false.setText(_translate("MainWindow", "radioButton_yolo_half_false"))
        self.radioButton_yolo_nms_false.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_yolo_line_2.setText(_translate("MainWindow", "RadioButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
